# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='is_draft',
            field=models.BooleanField(default=True),
        ),
    ]
